### PR TITLE
AP completion page styling/display

### PR DESCRIPTION
**Pull request by emcelroy**
PT Stories: 

https://www.pivotaltracker.com/story/show/177147747
https://www.pivotaltracker.com/story/show/177287947

[#17714774]
[#177287947]

### CODE REVIEW

**Comment by emcelroy** [comment]
@dougmartin @knowuh Getting the failing codecov check to pass requires getting an automated test to answer all the questions in a Sequence. I tried to make that work, but had limited success. The iframes within iframes defeated me. 

I think it's best to let the .1% drop in coverage go for now, but let me know if you think otherwise.

**Comment by knowuh** [comment]
@emcelroy -- This looks good.  Could you please merge the latest master branch into your branch 177147747-ap-completion-page-styling and then push that back up so the file diffs are easier to read here?  Thank you!

**Comment by emcelroy** [comment]
@knowuh When I do `git merge master` I get the message "Already up to date." I tried pushing again anyway for the heck of it, but got the message "Everything up to date." 

Sorry, I must've messed something up. There was a point where I made a change and when I tried to push it, I strangely got a message saying the remote branch was ahead of my local branch. I did a `git pull` and merged (You can see that in the commit history "Merge remote-tracking branch...", commit d974c0a492c8f0f3c5f24c8d525e1d0b8f2d80bf). Do you know if there's some other way I can get the diffs easier to read?

**Comment by knowuh** [comment]
I looked at this with Scott and Doug and we think that github is just confused.  looks good.

**Pull request merged**
