### PR TITLE
remove orange bar

### PR DESCRIPTION
**Pull request by mklewandowski**
Remove orange warning bar from the activity player.

### CODE REVIEW

**Comment by scytacki** [comment]
I don't think we should merge this until we have the report service updated so we can actually save production data. 

Right now someone can use the activity-player in production, but their data will be saved to the `report-service-dev` firestore database. That'd be bad is someone actually used this with students and their data was in the dev database.

**Comment by mklewandowski** [comment]
> I don't think we should merge this until we have the report service updated so we can actually save production data.
> 
> Right now someone can use the activity-player in production, but their data will be saved to the `report-service-dev` firestore database. That'd be bad is someone actually used this with students and their data was in the dev database.

I'm also wondering about the plugin links (less impactful).  Glossary is still pointing at master and I was going to move TE to do the same (to make dev easier), but if we're moving to production, both plugins should point to stable, release versions.

**Comment by scytacki** [comment]
Yeah good point about the plugin links, we have a story in Orange to deal with the plugin links. It is currently scheduled before the production release.

**Comment by mklewandowski** [comment]
> Yeah good point about the plugin links, we have a story in Orange to deal with the plugin links. It is currently scheduled before the production release.

Good to know.  I won't touch them in the meantime.

**Review by kswenson — APPROVED** [review]
👍 LGTM

**Review by eireland — APPROVED** [review]
Looks good. It was nice to see it without the warning banner!

**Pull request closed without merging**
